### ISSUE TITLE
Question - use of std::vector in esp8266 environment

### ISSUE THREAD

**Issue by sidoh** [neman-io/Bleeper#1] opened 2017-12-05 21:56 UTC
Thanks so much for this library.  It looks like a really beautiful interface, and I'm eager to use it in my projects.

I think pulling in `std::vector` causes conflicts because the macros `min` and `max`, which are defined here, are also defined elsewhere in the ESP8266 Arduino SDK.  (Or, at least, that's my understanding).

Reference: https://github.com/esp8266/Arduino/issues/2549

I've tried stuffing Arduino.h before Bleeper.h in my main, which solves the original issue, but then I get other wacky compile errors in a different library I'm using (GxEPD).

Wondering if this is something you've ran into before, and if you have a suggested workaround?  Is there a way to make Bleeper robust to header inclusion ordering?

**Comment by dernster** [comment] 2017-12-06 01:57
Thanks @sidoh !

I've experienced those issues but solved them reordering the `include` statements. Is the original compiling error thrown in one of your source files because of using `min` or `max`? It seems that you can use `_min` & `_max` to solve this [(reference)](https://github.com/esp8266/Arduino/issues/263#issuecomment-195925193)

If we are sure that the problem is caused by the usage of `std::vector` I could implement my own version of it. But maybe I would need to do the same for `std::map` ?

Are you using Arduino IDE? Do you have a repo I can checkout?

**Comment by sidoh** [comment] 2017-12-06 07:46
Ah, I think one of my sources does use min/max.  But I'm quite sure that other libraries I'm using are using them too (GxEPD and Adafruit_GFX).  Do you think that would matter?  I could fork and patch them, but obviously would prefer not to.

Do you know which libraries you've reordered in order to fix the problem?

I definitely can't say I'm sure that `std::vector` causes the problem, but it does seem others have seen the same compile errors I have when trying to use it.  I'll try harder to dig into the errors.

I'm using PlatformIO.  I've not pushed the code I'm working on yet, but I can do that shortly.

**Comment by dernster** [comment] 2017-12-06 11:06
Hmm I think I tried with the `Arduino.h` include trick. Try to include Bleeper at the end of your include list and use `_min` & `_max` in your code. Let me know when your repo is up so I can take look :)

[See this issue](https://github.com/ZinggJM/GxEPD/issues/17)

**Comment by sidoh** [comment] 2017-12-10 09:48
Thanks @dernster!

I dug a little more on this issue, and seems like this is a well-known (albeit poorly documented) fact that stdlibc++ `vector` is incompatible with Arduino without some monkey-patching.  Other libraries seem to hack around this [with stuff like this](https://github.com/me-no-dev/ESPAsyncWebServer/blob/8139925eb9b5d0d159d36edc03a409788138a627/src/WebResponseImpl.h#L24-L29).

Feels a little gross, but looks like it might get the job done.

I got the [code I was working](https://github.com/sidoh/epaper_templates) on up, but I backed out the Bleeper stuff halfway through.  Memory on ESP8266 was super tight so I had to switch to an ESP32.  Haven't tried it yet, but any idea if Bleeper is compatible with the ESP32 SDK?

**Comment by dernster** [comment] 2017-12-17 20:04
Hi @sidoh !

It seems that regardless of undefining those min & max macros the problem remains. The only way I could compile Bleeper along with GxEPD was including the Bleeper header after the GxEPD ones.

I think that the most robust solution at this point for libraries that use those macros is replacing them for `_min` & `_max`. If you agree with this I'll be closing this issue.

Regarding the ESP32, right now it isn't supported. Do you have any recommendation for a WebServer working on esp8266 & esp32? My plan is to add this asap :)

**Comment by sidoh** [comment] 2017-12-18 17:47
I agree Thanks for looking into it :)

The owner of the GxEPD library just pushed a change to not use `min` and `max`, which I expect will fix my particular problem.

[ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer/) supports both ESP8266 and ESP32.  It's asynchronous so the internal modeling is a little different, but it actually feels a little cleaner to me.

It uses two different TCP libraries for the ESP8266 and ESP32 and PlatformIO doesn't handle that super nicely.  Had to include the lib per-platform and exclude the other platform libs.  Example here:

https://github.com/sidoh/epaper_templates/blob/master/platformio.ini

**Closed as completed** 2017-12-21 03:52 UTC
